### ISSUE TITLE
Some plugin's action bar not works

### ISSUE THREAD

**Issue by Szabolcs24** [gepron1x/minimessage-anywhere#10]
Somehow the plugin not really wants to replace some actionbar. For example the BattlePass plugin's one, simply the raw formating shows up only.

**Comment by gepron1x** [comment]
I can't guarantee that minimessage-anywhere will work with all plugins. Some of them send messages that way MMA can't handle it, and unfortunately i can't do anything with that. It seems that BattlePass is the one. I can only guess because it's code is closed-source and plugin is paid.
