### ISSUE TITLE
MMA не взаимодействует с плагином AnimatedScoreboard (HEX работает только в названии скорборда)

### ISSUE THREAD

**Issue by IlyaDityatyev** [gepron1x/minimessage-anywhere#2]
Версия сервера: 1.17.1 only
Ядро: Patina (Включает в себя солянку из airplane, bukkit, purpur, paper, spigot, yatopia(Особо во всём этом не разбираюсь, но просто файлы этих конфигов лежат в корне сервера))

![Minecraft_ 1 17 1 - Multiplayer (3rd-party Server) 18 01 2022 2_34_58](https://user-images.githubusercontent.com/95450229/149847877-b3804ff2-5d3f-43bc-bbc4-52223239289b.png)

Часть конфига плагина AnimatedScoreboard:

display:
    title:
      text:
      - "<#cc6600>> <#330099>Eternal<#cc6600> <"
      random: false
      interval: -1
    line-1:
      text:
      - " "
      random: false
      interval: -1
      score: 0  
    line-2:
      text:
      - " Вы - %luckperms_prefix%"
      random: false
      interval: -1
      score: 0
    line-3:
      text:
      - " "
      random: false
      interval: -1
      score: 0
    line-4:
      text:
      - "<yellow>Баланс:"    
      random: false
      interval: -1
      score: 0
    line-5:
      text:
      - "<#ffcc00> >> <#cc6600>%vault_eco_balance%"
      random: false
      interval: 60
      score: 0

P.s. Не отрицаю, что, возможно я где-то не досмотрел документацию

**Comment by gepron1x** [comment]
Привет. Сомневаюсь, что это можно исправить на стороне моего плагина. Это ошибка, скорее всего, будет распространена на большинстве плагинов для scoreboard'а. Дело в том, что почти все плагины разбивают строку на 3 части, чтобы она поместилась у игрока на экране (ограничение майнкрафта, которое, кстати, убрали начиная с 1.18, но плагинам, поддерживающим legacy версии приходится делать это). Из-за того что строка разделена, MMA не может обработать строку полноценно. Такой танец с бубном.
