### ISSUE TITLE
Plugin will not create folder

### ISSUE THREAD

**Issue by DarkmayGOD** [gepron1x/minimessage-anywhere#5]
Hello, .jar file is in plugin folder, I restarted server, and still nothing was created.

I don't see in /plugins the plugin. 

How to fix?

Paper 1.18.2

**Comment by gepron1x** [comment]
Hello, plugin probably did not load. Please post full log.

**Comment by DarkmayGOD** [comment]
Console https://pastes.dev/AzLcNdV7V3

**Comment by DarkmayGOD** [comment]
Plugin is loaded, is it green, but it is not working... See the pastes.dev please, and help me :(

**Comment by DarkmayGOD** [comment]
![image](https://user-images.githubusercontent.com/63445825/180046998-ebf1cb08-0d1e-4d3b-99a8-88c9c47fb5eb.png)

**Comment by gepron1x** [comment]
That depends on your on parsingStrategy and prefix and suffix, which you defined in conifg.
Please take a note that plugin may not work in scoreboard, due to the limitations of minecraft (text is being split into 3 parts)

**Comment by DarkmayGOD** [comment]
I have in config prefix: '[mm]'

**Comment by DarkmayGOD** [comment]
So I only need to put [mm] to the scoreboard?

**Comment by DarkmayGOD** [comment]
Tried with the luckperms too aswell.

**Comment by gepron1x** [comment]
[mm]Text[/mm]

**Comment by DarkmayGOD** [comment]
But I need rank of player

**Comment by DarkmayGOD** [comment]
with %luckperms%

**Comment by DarkmayGOD** [comment]
![image](https://user-images.githubusercontent.com/63445825/180055300-84ef39f6-53bd-497e-a63d-0c025306dbc8.png)

**Comment by gepron1x** [comment]
Include the rank placeholder between prefix and suffix.

**Comment by DarkmayGOD** [comment]
![image](https://user-images.githubusercontent.com/63445825/180056816-c69cfbbc-a1a3-4aff-a2be-1a88c7dc2654.png)

**Comment by DarkmayGOD** [comment]
Same.

**Comment by gepron1x** [comment]
try doing this in the chat

**Comment by DarkmayGOD** [comment]
Its working, but I cannot insert placeholder in the chat xD

**Comment by DarkmayGOD** [comment]
I have animated scoreboard.
