### ISSUE TITLE
action bar is not working

### ISSUE THREAD

**Issue by erkutay07** [gepron1x/minimessage-anywhere#6]
![image](https://user-images.githubusercontent.com/58345549/213517718-5ee87c71-827d-494b-857e-f78aaf0d4b8c.png)

using heroaction
version: paper-265(1.19.2-r0.1)

config:
![image](https://user-images.githubusercontent.com/58345549/213517811-5f8ffdc7-dba3-4f6b-8bd6-30b2c2dbc171.png)

**Comment by gepron1x** [comment]
Hm, i think i know what's the problem. Try using vanilla command  /title to send action bar and see if it works

**Comment by erkutay07** [comment]
yes it does

**Comment by gepron1x** [comment]
> yes it does

with MiniMessage tags you mean?

**Comment by erkutay07** [comment]
yes

**Comment by gepron1x** [comment]
I'm sorry. The problem is in a way how heroactions sends the actionbar. MiniMessageAnywhere can't catch that.
