### ISSUE TITLE
Error when enabling the plugin on Paper 1.16.5

### ISSUE THREAD

**Issue by AdoreRose** [gepron1x/minimessage-anywhere#8]
Java version: 16.0.2
Server: git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugins: MiniMessageAnywhere v2.2.2, ProtocolLib v5.0.0-SNAPSHOT-b608

An error appears when loading the plugin: java.lang.UnsupportedClassVersionError: me/gepron1x/minimessageanywhere/MiniMessageAnywhere has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0.

Newer versions of Java, the server does not start.

**Comment by gepron1x** [comment]
Well, you need to run the server on java 17
